packageNum: 624
packageIdent: knb-lter-cap.624.3
title: Long-term monitoring of stormwater runoff and water quality in urbanized watersheds of the greater Phoenix metropolitan area, ongoing since 2008
